name: pocket_biz_manager
description: A new Flutter project for managing small business operations.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted for modern Flutter

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3 # Added path package
  intl: ^0.18.1
  provider: ^6.1.1
  # image_picker: ^1.0.4 # Add later
  # flutter_barcode_scanner: ^2.0.0 # Add later
  # pdf: ^3.10.4 # Add later
  # share_plus: ^7.2.1 # Add later
  # permission_handler: ^11.0.1 # Add later

  cupertino_icons: ^1.0.2 # Usually included with new Flutter projects

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Or latest version

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An example of adding data from package dependencies to your application
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
